# Generated by Django 4.2.8 on 2024-01-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
